###
GET http://localhost:8080/auth/getUser
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImV4cCI6MTY1ODIzMzY4MiwiaWF0IjoxNjU4MjMwMDgyLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay11NDN6OUBqYXZhZmlyc3Rwcm9qZWN0LTRlMDJkLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic3ViIjoiZmlyZWJhc2UtYWRtaW5zZGstdTQzejlAamF2YWZpcnN0cHJvamVjdC00ZTAyZC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInVpZCI6ImRZekRuQ3VXSnNSU1NzQVVjZEc4WVZCV0U0RzIifQ.N9Gn17-3aIjsQhIuwkGIK7PZ7lDJcXi7sCE6cFLgwoJN_8KsvdBVzqhZQjybs6srTKehopOlz5o2TZNRi5kpxyBefKkanLfqEIYhHoJPBe3xhdwE2sxZm1-mH4KBzy7aUZWTBvFJS-cJP4qEkT82tvxMl8n0ORA2nVHSCFIfvbb0uvCghX-nYd3dPDvXHuorUGkDKxAsGOb8P49B9WeXSCOWZK7woqSneTOTlaPophxy4dXf6ajA_js7CocAXorRiCV8f8fgjIQtfc_0IAPL-vm2feNE-eyYsO5SeE7DnXvmqSL9eQrkR6uJgDslc_Yfx_EZUJN8NmzGuVLPMwhrHw

###
POST http://localhost:8080/register
content-type: application/json

{
    "email": "test@mail.com",    
    "password": "testpassword"
}